version: 2.1
jobs:
  build:
    working_directory: ~/source
    docker:
      - image: ruby:2.6.0
    steps:
      - checkout
      - run: ./scripts/ci/common/install-openjdk.sh
      - run: ./scripts/ci/steps/build.sh
  test:
    working_directory: ~/source
    docker:
      - image: ruby:2.6.0
    steps:
      - checkout
      - run: ./scripts/ci/common/install-openjdk.sh
      - run: ./scripts/ci/steps/test.sh

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
